export const ActionTypes={
    SET_COLLECTION_IMAGE:"SET_COLLECTION_IMAGE",
    SET_IMAGE_ARR:"SET_IMAGE_ARR",
    START_FETCHING:"START_FETCHING",
    STOP_FETCHING:"STOP_FETCHING",
    SET_MJ_PROGRESS:"SET_MJ_PROGRESS"
}